name             'scpr-ftp'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures vanilla-cookbook'
long_description 'Installs/Configures vanilla-cookbook'
version          '0.2.2'
